package service

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/sys/windows"
	"golang.org/x/sys/windows/svc"
	"golang.org/x/sys/windows/svc/mgr"

	"network-tracker/internal/anomaly"
	"network-tracker/internal/config"
	"network-tracker/internal/logger"
	"network-tracker/internal/monitor"
	"network-tracker/internal/storage"
)

const (
	DefaultServiceName        = "NetworkTracker"
	DefaultServiceDisplayName = "Network Tracker Monitoring Service"
	DefaultServiceDescription = "24/7 background network connection monitor, ephemeral process tracker, and anomaly detection system."
)

// GetServiceName returns the configured service name or fallback default
func GetServiceName(cfg *config.Config) string {
	if cfg != nil && cfg.Service.Name != "" {
		return cfg.Service.Name
	}
	return DefaultServiceName
}

// GetServiceDisplayName returns the configured display name or fallback default
func GetServiceDisplayName(cfg *config.Config) string {
	if cfg != nil && cfg.Service.DisplayName != "" {
		return cfg.Service.DisplayName
	}
	return DefaultServiceDisplayName
}

// GetServiceDescription returns the configured description or fallback default
func GetServiceDescription(cfg *config.Config) string {
	if cfg != nil && cfg.Service.Description != "" {
		return cfg.Service.Description
	}
	return DefaultServiceDescription
}

// SetupWorkingDirectory automatically resolves the working directory to the project root.
// Essential because Windows Services start by default in C:\Windows\System32,
// and 'go run' executes from a temporary build folder in AppData\Local\Temp.
func SetupWorkingDirectory() {
	// 1. If config.json is present in the current working directory, keep it
	if _, err := os.Stat("config.json"); err == nil {
		return
	}

	// 2. If config.json is in a parent directory (e.g. executing from dist/ or cmd/tracker)
	if _, err := os.Stat("../config.json"); err == nil {
		_ = os.Chdir("..")
		return
	}
	if _, err := os.Stat("../../config.json"); err == nil {
		_ = os.Chdir("../..")
		return
	}

	// 3. If running as a compiled binary (such as Windows Service invoked from System32)
	exePath, err := os.Executable()
	if err != nil {
		return
	}
	exeDir := filepath.Dir(exePath)

	// Ignore temporary directories generated by "go run"
	lowerDir := strings.ToLower(exeDir)
	if strings.Contains(lowerDir, "go-build") || (strings.Contains(lowerDir, "temp") && !strings.Contains(lowerDir, "dist")) {
		return
	}

	// If config.json is located alongside the executable
	if _, err := os.Stat(filepath.Join(exeDir, "config.json")); err == nil {
		_ = os.Chdir(exeDir)
		return
	}

	// If the binary is in a subdirectory (e.g. dist/), step up to parent
	parentDir := filepath.Dir(exeDir)
	if _, err := os.Stat(filepath.Join(parentDir, "config.json")); err == nil {
		_ = os.Chdir(parentDir)
		return
	}
}

// TrackerWindowsService implements svc.Handler to communicate with Windows SCM
type TrackerWindowsService struct {
	cfg *config.Config
}

// NewTrackerWindowsService initializes the Windows Service handler
func NewTrackerWindowsService(cfg *config.Config) *TrackerWindowsService {
	return &TrackerWindowsService{cfg: cfg}
}

// Execute is called by the Windows Service Control Manager (SCM) when starting the service
func (s *TrackerWindowsService) Execute(args []string, r <-chan svc.ChangeRequest, changes chan<- svc.Status) (ssec bool, errno uint32) {
	const cmdsAccepted = svc.AcceptStop | svc.AcceptShutdown
	changes <- svc.Status{State: svc.StartPending}

	// Ensure working directory is aligned with project root
	SetupWorkingDirectory()

	// Record PID file for tracking
	_ = WritePID()
	defer RemovePID()

	// Initialize core monitoring engines
	dnsResolver := monitor.NewDNSResolver(s.cfg.DNS.Enabled, s.cfg.DNS.CacheSize, s.cfg.DNS.TimeoutMs)
	lifecycle := monitor.NewLifecycleCache(60 * time.Second)
	defer lifecycle.Stop()

	bandwidth := monitor.NewBandwidthTracker()
	poller := monitor.NewConnectionPoller(s.cfg, dnsResolver, lifecycle, bandwidth)
	detector := anomaly.NewAnomalyDetector(s.cfg)

	logWriter, err := logger.NewLogger(s.cfg)
	if err != nil {
		return false, 1
	}
	defer logWriter.Close()

	var store *storage.Storage
	if s.cfg.Database.Enabled {
		if st, err := storage.NewStorage(s.cfg.Database.DbPath); err == nil {
			store = st
			defer store.Close()
		}
	}

	interval := time.Duration(s.cfg.Monitor.ScanIntervalMs) * time.Millisecond
	if interval < 50*time.Millisecond {
		interval = 200 * time.Millisecond
	}

	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	// Setup Config Hot-Reload watcher
	cfgFilePath := config.ResolveConfigPath("config.json")
	var lastCfgMod time.Time
	if info, err := os.Stat(cfgFilePath); err == nil {
		lastCfgMod = info.ModTime()
	}
	tickCounter := 0

	// Report to Windows SCM that the service is running
	changes <- svc.Status{State: svc.Running, Accepts: cmdsAccepted}

	firstScan := true
	for {
		select {
		case <-ticker.C:
			tickCounter++
			// Periodically check for config.json modifications (every ~1s)
			if tickCounter%5 == 0 {
				if modified, newMod := config.CheckModified(cfgFilePath, lastCfgMod); modified {
					lastCfgMod = newMod
					newCfg, err := config.LoadConfig(cfgFilePath)
					if err == nil && newCfg != nil {
						s.cfg = newCfg
						poller.UpdateConfig(newCfg)
						detector.UpdateConfig(newCfg)
						dnsResolver.UpdateConfig(newCfg.DNS.Enabled)
						_ = logWriter.UpdateConfig(newCfg)

						newInterval := time.Duration(newCfg.Monitor.ScanIntervalMs) * time.Millisecond
						if newInterval < 50*time.Millisecond {
							newInterval = 200 * time.Millisecond
						}
						if newInterval != interval {
							interval = newInterval
							ticker.Reset(interval)
						}

						_ = logWriter.LogSystem("All configuration parameters reloaded automatically from config.json (Hot-Reload)")
					} else if err != nil {
						_ = logWriter.LogSystem(fmt.Sprintf("Warning: Failed to reload config.json: %v (keeping active config)", err))
					}
				}
			}

			conns, err := poller.Poll()
			if err != nil {
				continue
			}

			if firstScan {
				firstScan = false
				_ = logWriter.LogSystem(fmt.Sprintf("Service started. Baseline established with %d active sockets. Tracking real-time changes...", len(conns)))
				continue
			}

			for _, c := range conns {
				// Record real-time changes only (CONNECT, CLOSE, new LISTEN)
				if c.IsDelta {
					_ = logWriter.LogConnection(c)
					if store != nil {
						_ = store.SaveConnection(c)
					}
				}

				// Deduplicated anomaly detection
				newAlerts := detector.CheckNewAlerts(c)
				for _, alt := range newAlerts {
					_ = logWriter.LogAlert(alt)
					if store != nil {
						_ = store.SaveAlert(alt)
					}
				}
			}

		case c := <-r:
			switch c.Cmd {
			case svc.Interrogate:
				changes <- c.CurrentStatus
			case svc.Stop, svc.Shutdown:
				_ = logWriter.LogSystem("Service stopping safely...")
				// Report to Windows SCM that service stop is pending
				changes <- svc.Status{State: svc.StopPending}
				return false, 0
			default:
			}
		}
	}
}

// RunAsWindowsService executes the application under the supervision of Windows SCM
func RunAsWindowsService(cfg *config.Config) error {
	serviceName := GetServiceName(cfg)
	return svc.Run(serviceName, NewTrackerWindowsService(cfg))
}

// InstallService registers the service into Windows SCM (Administrator privileges required)
func InstallService(exePath string, cfg *config.Config) error {
	m, err := mgr.Connect()
	if err != nil {
		return fmt.Errorf("cannot connect to Service Control Manager (Administrator privileges required): %w", err)
	}
	defer m.Disconnect()

	serviceName := GetServiceName(cfg)
	displayName := GetServiceDisplayName(cfg)
	description := GetServiceDescription(cfg)

	s, err := m.OpenService(serviceName)
	if err == nil {
		s.Close()
		return fmt.Errorf("service '%s' already exists on system", serviceName)
	}

	absExe, err := filepath.Abs(exePath)
	if err != nil {
		absExe = exePath
	}

	serviceCfg := mgr.Config{
		ServiceType:  windows.SERVICE_WIN32_OWN_PROCESS,
		StartType:    mgr.StartAutomatic, // Automatically start on Windows boot
		ErrorControl: mgr.ErrorNormal,
		DisplayName:  displayName,
		Description:  description,
	}

	s, err = m.CreateService(serviceName, absExe, serviceCfg)
	if err != nil {
		return fmt.Errorf("failed to create service: %w", err)
	}
	defer s.Close()

	return nil
}

// UninstallService removes the service from Windows SCM (Administrator privileges required)
func UninstallService(cfg *config.Config) error {
	m, err := mgr.Connect()
	if err != nil {
		return fmt.Errorf("cannot connect to SCM (Administrator privileges required): %w", err)
	}
	defer m.Disconnect()

	serviceName := GetServiceName(cfg)
	s, err := m.OpenService(serviceName)
	if err != nil {
		return fmt.Errorf("service '%s' is not installed", serviceName)
	}
	defer s.Close()

	// Stop service first if running
	status, err := s.Query()
	if err == nil && status.State == svc.Running {
		_, _ = s.Control(svc.Stop)
		time.Sleep(1 * time.Second)
	}

	if err := s.Delete(); err != nil {
		return fmt.Errorf("failed to delete service: %w", err)
	}

	return nil
}

// StartWindowsService starts the service via SCM
func StartWindowsService(cfg *config.Config) error {
	m, err := mgr.Connect()
	if err != nil {
		return fmt.Errorf("cannot connect to SCM: %w", err)
	}
	defer m.Disconnect()

	serviceName := GetServiceName(cfg)
	s, err := m.OpenService(serviceName)
	if err != nil {
		return fmt.Errorf("service '%s' is not installed, run 'network-tracker service install'", serviceName)
	}
	defer s.Close()

	if err := s.Start(); err != nil {
		return fmt.Errorf("failed to start service: %w", err)
	}

	return nil
}

// StopWindowsService stops the service via SCM
func StopWindowsService(cfg *config.Config) error {
	m, err := mgr.Connect()
	if err != nil {
		return fmt.Errorf("cannot connect to SCM: %w", err)
	}
	defer m.Disconnect()

	serviceName := GetServiceName(cfg)
	s, err := m.OpenService(serviceName)
	if err != nil {
		return fmt.Errorf("service '%s' is not installed", serviceName)
	}
	defer s.Close()

	status, err := s.Control(svc.Stop)
	if err != nil {
		return fmt.Errorf("failed to stop service: %w", err)
	}

	timeout := time.Now().Add(10 * time.Second)
	for status.State != svc.Stopped {
		if time.Now().After(timeout) {
			return fmt.Errorf("timed out waiting for service to stop")
		}
		time.Sleep(300 * time.Millisecond)
		status, err = s.Query()
		if err != nil {
			return fmt.Errorf("error querying service status: %w", err)
		}
	}

	return nil
}

// QueryWindowsServiceStatus queries service status from SCM (standard user access, no admin required)
func QueryWindowsServiceStatus(cfg *config.Config) (string, error) {
	scm, err := windows.OpenSCManager(nil, nil, windows.SC_MANAGER_CONNECT)
	if err != nil {
		return "UNKNOWN", fmt.Errorf("cannot connect to SCM: %w", err)
	}
	defer windows.CloseServiceHandle(scm)

	serviceName := GetServiceName(cfg)
	sName, err := windows.UTF16PtrFromString(serviceName)
	if err != nil {
		return "UNKNOWN", err
	}

	hService, err := windows.OpenService(scm, sName, windows.SERVICE_QUERY_STATUS)
	if err != nil {
		if errors.Is(err, windows.ERROR_SERVICE_DOES_NOT_EXIST) {
			return "NOT_INSTALLED", nil
		}
		return "NOT_INSTALLED", nil
	}
	defer windows.CloseServiceHandle(hService)

	var status windows.SERVICE_STATUS
	err = windows.QueryServiceStatus(hService, &status)
	if err != nil {
		return "ERROR", err
	}

	switch status.CurrentState {
	case windows.SERVICE_RUNNING:
		return "RUNNING", nil
	case windows.SERVICE_STOPPED:
		return "STOPPED", nil
	case windows.SERVICE_START_PENDING:
		return "START_PENDING", nil
	case windows.SERVICE_STOP_PENDING:
		return "STOP_PENDING", nil
	case windows.SERVICE_PAUSED:
		return "PAUSED", nil
	default:
		return fmt.Sprintf("STATE_%d", status.CurrentState), nil
	}
}
